export const dummyScoreData = () => {
  return [
    {name: "Chris", matrix: "8x8", matches: "4", score: "20", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "3x3", matches: "3", score: "10", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x2", matches: "4", score: "14", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "4x7", matches: "7", score: "33", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", matches: "2", score: "56", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "5x5", matches: "5", score: "12", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", matches: "4", score: "20", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "3x3", matches: "3", score: "10", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x2", matches: "4", score: "14", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "4x7", matches: "7", score: "33", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", matches: "2", score: "56", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "5x5", matches: "5", score: "12", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", matches: "4", score: "20", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "3x3", matches: "3", score: "10", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x2", matches: "4", score: "14", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "4x7", matches: "7", score: "33", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", matches: "2", score: "56", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "5x5", matches: "5", score: "12", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", matches: "4", score: "20", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "3x3", matches: "3", score: "10", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x2", matches: "4", score: "14", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "4x7", matches: "7", score: "33", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", matches: "2", score: "56", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "5x5", matches: "5", score: "12", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", matches: "4", score: "20", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "3x3", matches: "3", score: "10", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x2", matches: "4", score: "14", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "4x7", matches: "7", score: "33", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", matches: "2", score: "56", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "5x5", matches: "5", score: "12", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", matches: "4", score: "20", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "3x3", matches: "3", score: "10", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x2", matches: "4", score: "14", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "4x7", matches: "7", score: "33", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", matches: "2", score: "56", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "5x5", matches: "5", score: "12", date: `${new Date().toUTCString()}`},
  ]
}
