export const dyScoScorereData = () => {
  return [
    {name: "Chris", matrix: "8x8", numberOfMatches: "4", score: "20", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "3x3", numberOfMatches: "3", score: "10", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x2", numberOfMatches: "4", score: "14", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "4x7", numberOfMatches: "7", score: "33", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", numberOfMatches: "2", score: "56", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "5x5", numberOfMatches: "5", score: "12", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", numberOfMatches: "4", score: "20", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "3x3", numberOfMatches: "3", score: "10", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x2", numberOfMatches: "4", score: "14", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "4x7", numberOfMatches: "7", score: "33", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", numberOfMatches: "2", score: "56", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "5x5", numberOfMatches: "5", score: "12", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", numberOfMatches: "4", score: "20", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "3x3", numberOfMatches: "3", score: "10", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x2", numberOfMatches: "4", score: "14", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "4x7", numberOfMatches: "7", score: "33", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", numberOfMatches: "2", score: "56", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "5x5", numberOfMatches: "5", score: "12", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", numberOfMatches: "4", score: "20", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "3x3", numberOfMatches: "3", score: "10", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x2", numberOfMatches: "4", score: "14", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "4x7", numberOfMatches: "7", score: "33", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", numberOfMatches: "2", score: "56", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "5x5", numberOfMatches: "5", score: "12", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", numberOfMatches: "4", score: "20", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "3x3", numberOfMatches: "3", score: "10", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x2", numberOfMatches: "4", score: "14", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "4x7", numberOfMatches: "7", score: "33", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", numberOfMatches: "2", score: "56", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "5x5", numberOfMatches: "5", score: "12", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", numberOfMatches: "4", score: "20", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "3x3", numberOfMatches: "3", score: "10", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x2", numberOfMatches: "4", score: "14", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "4x7", numberOfMatches: "7", score: "33", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "8x8", numberOfMatches: "2", score: "56", date: `${new Date().toUTCString()}`},
    {name: "Chris", matrix: "5x5", numberOfMatches: "5", score: "12", date: `${new Date().toUTCString()}`},
  ]
}
